# Uncomment the following lines to enable the Corne RGB Underglow
# CONFIG_ZMK_RGB_UNDERGLOW=y
# CONFIG_WS2812_STRIP=y

# Uncomment the following line to enable the Corne OLED Display
# CONFIG_ZMK_DISPLAY=y

# Enable Display
CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_EXT_POWER=y
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_CUSTOM=y

# For nice!view only, uncomment the next line
# CONFIG_NICE_EPAPER_ON=y
# CONFIG_NICE_EPAPER_LUT_COUNT=3
# Disable animations to save battery
CONFIG_NICE_VIEW_GEM_ANIMATION=y
# Enable WPM tracking on the display
CONFIG_ZMK_WPM=n

